<?php
/**
 * @copyright Copyright © 2021 Magepow. All rights reserved.
 * @author    Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
/**
 * @var \Magepow\AjaxCompare\Block\Js $block
 */
?>
<?php 
$helper = $this->helper('Magepow\AjaxCompare\Helper\Data');
if(!$helper->getConfigModule('general/enabled')) return;
?>
<script type="text/x-magento-init">
{
    "body": {
        "magepow/ajaxcompare" : {
            "popupTTL"       : "<?php echo $helper->getConfigModule("general/popupttl") ?>",
            "showLoader"     : "<?php echo $helper->getConfigModule('general/loader') ?>"        
        }
    }
}
</script>