<?php
/**
 * @copyright Copyright © 2021 Magepow. All rights reserved.
 * @author    Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
/**
 * @var \Magento\Catalog\Block\Product\AbstractProduct $block
 */
?>

<?php 
$helper = $this->helper('Magepow\AjaxCompare\Helper\Data');
if(!$helper->getConfigModule('general/enabled')) return;
$_product = $block->getProduct();
$imageDisplayArea = 'category_page_grid';
$productImage = $block->getImage($_product, $imageDisplayArea);
$message = $helper->getConfigModule('general/message');
?>
<div class="mgp-compare-popup-border ajaxcompare-success-box">
    <div class="ajax-compare-image">
        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
           class="product photo product-item-photo"
           tabindex="-1">
            <?= $productImage->toHtml() ?>
        </a>
        <h2 class="product-name"><?php echo $_product->getName() ?></h2>
    </div>
    <h3 class="mgp-message-successs"><?php echo $message ? $message : __('You added this product to the comparison list') ?></h3>
    <div class="ajaxcompare-buttons">
        <button type="button" id="ajaxcompare_btn_close_popup" class="action primary mgp-compare-close" title="<?php echo __('Close') ?>">
            <span><?php echo __('Close ') ?></span>
            <?php
                 if ($popupTTL = $helper->getConfig("magepow_ajaxcompare/general/popupttl")) {?>
                 (<span class="compare-autoclose-countdown"><?php echo $popupTTL ?></span>)
                 <?php }?>
        </button>
        <button type="button" id="ajaxcompare_checkout" class="action focus primary"
                title="<?php echo __('View Comparison') ?>"
                onClick="window.location='<?php echo $block->getUrl('catalog/product_compare/index/'); ?>'">
            <span><?php echo __('View Comparison List') ?></span>
        </button>
    </div>
</div>
