<?php
/**
 * @copyright Copyright © 2021 Magepow. All rights reserved.
 * @author    Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
/**
 * @var \Magento\Catalog\Block\Product\View $block
 */
?>

<?php 
$helper = $this->helper('Magepow\AjaxCompare\Helper\Data');
$_product = $block->getProduct(); 
?>
<div class="mgp-compare-popup-border ajaxcompare-success-box">
    <?php echo $block->getChildHtml('ajaxcompare.message'); ?>

    <h2 class="product-name"><?php echo $_product->getName() ?></h2>
    <img src="<?php echo $helper->getBaseUrlMedia().'catalog/product/'.$_product->getImage() ;?>" alt="<?php echo $_product->getName() ?>">
    <div class="ajaxcompare-buttons">
        <button type="button" id="ajaxcompare_btn_close_popup" class="action primary mgp-compare-close"
                title="<?php echo __('Close') ?>">
            <span><?php echo __('Close ') ?></span>
            
            <?php
                 if ($popupTTL = $helper->getConfig("magepow_ajaxcompare/general/popupttl")) {?>
                 (<span class="compare-autoclose-countdown"><?php echo $popupTTL ?></span>)
                 <?php }?>
        </button>
        <button type="button" id="ajaxcompare_checkout" class="action focus primary"
                title="<?php echo __('View Comparison') ?>"
                onClick="window.location='<?php echo $block->getUrl('catalog/product_compare/index/'); ?>'">
            <span><?php echo __('View Comparison') ?></span>
        </button>
    </div>
</div>
