<?php
/**
 * 
 * @category: Magepow
 * @Copyright (c) 2014 Magepow  (<https://www.magepow.com>)
 * @authors: Magepow (<magepow<support@magepow.com>>)
 * @license: <http://www.magepow.com/license-agreement>
 * @github: <https://github.com/magepow> 
 */

?>
<div id="mgp-compare-popup" class="mgp-compare-popup">
    <?php echo $block->getChildHtml('ajaxcompare.popup.wrapper'); ?>
</div>
